baseURL = 'https://shumi.cc/'
locale = 'en-us'
title = 'shumi project'
theme = 'hugo-PaperMod'

[params]
  env = "production"
  description = "Tu descripción"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.label]
  text = " "
  icon = "/images/logo.png"
  
  iconHeight = 70
  

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1
 
[[menu.main]]
  name = "Images"
  url = "/images/"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "/archives/"
  weight = 3